import { describe, expect, test } from "bun:test";
import type { TableRecord } from "@/lib/content/schemas";
import {
  type TableRegistrySourceRecord,
  verifyGeneratedTableRegistryState,
} from "@/lib/content/table-registry-verification";

function createTableRecord(id: string, subjectId: string): TableRecord {
  return {
    id,
    subjectId,
    columns: [
      {
        moduleId: subjectId,
        titleKey: `${id}.columns.primary`,
      },
    ],
    dimensions: [
      {
        id: "comparisonAxis",
        labelKey: `${id}.dimensions.primary`,
      },
    ],
    valueKeysByModuleId: {
      [subjectId]: {
        comparisonAxis: `${id}.values.primary`,
      },
    },
  };
}

function createSourceRecord(
  fileName: string,
  id: string,
  subjectId: string,
): TableRegistrySourceRecord {
  return {
    fileName,
    record: createTableRecord(id, subjectId),
  };
}

describe("table-registry-verification", () => {
  test("accepts matching generated output and runtime table ids", () => {
    const sourceRecords = [
      createSourceRecord(
        "alpha-comparison.json",
        "table.alpha-comparison",
        "module.alpha",
      ),
      createSourceRecord(
        "beta-comparison.json",
        "table.beta-comparison",
        "module.beta",
      ),
    ];

    const matchingGeneratedModuleSource = `// This file is generated by \`bun run generate:table-registry\`.
// Do not edit it by hand.

import alphaComparisonTableRecord from "@/content/registry/tables/alpha-comparison.json";
import betaComparisonTableRecord from "@/content/registry/tables/beta-comparison.json";

export const generatedTableRegistrySourceFiles = [
  "alpha-comparison.json",
  "beta-comparison.json",
] as const;

export const generatedTableRegistryPayloads = [
  alphaComparisonTableRecord,
  betaComparisonTableRecord,
] as const;
`;

    expect(
      verifyGeneratedTableRegistryState({
        sourceRecords,
        generatedModuleSource: matchingGeneratedModuleSource,
        runtimeTableRecords: sourceRecords.map(
          (record) => record.record as TableRecord,
        ),
      }),
    ).toEqual([]);
  });

  test("reports a missing generated module with an actionable error", () => {
    const problems = verifyGeneratedTableRegistryState({
      sourceRecords: [
        createSourceRecord(
          "alpha-comparison.json",
          "table.alpha-comparison",
          "module.alpha",
        ),
      ],
      generatedModuleSource: null,
      runtimeTableRecords: [
        createTableRecord("table.alpha-comparison", "module.alpha"),
      ],
    });

    expect(problems).toContain(
      "Missing generated table registry module at `src/lib/content/generated/table-registry.generated.ts`. Run `bun run generate:table-registry` and commit the result.",
    );
  });

  test("reports stale generated output and runtime ids that omit an on-disk table", () => {
    const sourceRecords = [
      createSourceRecord(
        "alpha-comparison.json",
        "table.alpha-comparison",
        "module.alpha",
      ),
      createSourceRecord(
        "beta-comparison.json",
        "table.beta-comparison",
        "module.beta",
      ),
    ];

    const problems = verifyGeneratedTableRegistryState({
      sourceRecords,
      generatedModuleSource: `// stale generated source`,
      runtimeTableRecords: [
        createTableRecord("table.alpha-comparison", "module.alpha"),
      ],
    });

    expect(problems).toContain(
      "Generated table registry module is out of sync with `src/content/registry/tables`. Run `bun run generate:table-registry` and commit the updated file.",
    );
    expect(problems).toContain(
      "Synchronous table runtime does not expose the same table ids as the on-disk registry. Expected: table.alpha-comparison, table.beta-comparison. Received: table.alpha-comparison.",
    );
  });
});
