export type TableRegistrySourceEntry = {
  fileName: string;
  importName: string;
  importPath: string;
};

const tableRegistryJsonSuffix = ".json";

function compareTableRegistryFileNames(left: string, right: string): number {
  return left.localeCompare(right);
}

function toGeneratedImportName(fileName: string): string {
  const stem = fileName.slice(0, -tableRegistryJsonSuffix.length);
  const camelStem = stem.replace(/-([a-z0-9])/g, (_, character: string) =>
    character.toUpperCase(),
  );

  return `${camelStem}TableRecord`;
}

export function createTableRegistrySourceEntries(
  fileNames: readonly string[],
  importBasePath = "@/content/registry/tables",
): TableRegistrySourceEntry[] {
  return [...fileNames]
    .filter((fileName) => fileName.endsWith(tableRegistryJsonSuffix))
    .sort(compareTableRegistryFileNames)
    .map((fileName) => ({
      fileName,
      importName: toGeneratedImportName(fileName),
      importPath: `${importBasePath}/${fileName}`,
    }));
}

export function renderGeneratedTableRegistryModule(
  entries: readonly TableRegistrySourceEntry[],
): string {
  const lines = [
    "// This file is generated by `bun run generate:table-registry`.",
    "// Do not edit it by hand.",
    "",
    ...entries.map(
      (entry) => `import ${entry.importName} from "${entry.importPath}";`,
    ),
    "",
    "export const generatedTableRegistrySourceFiles = [",
    ...entries.map((entry) => `  "${entry.fileName}",`),
    "] as const;",
    "",
    "export const generatedTableRegistryPayloads = [",
    ...entries.map((entry) => `  ${entry.importName},`),
    "] as const;",
    "",
  ];

  return lines.join("\n");
}
