import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import {
  getGeneratedContentRuntimeRoot,
  getProjectRoot,
  getRegistryCollectionRoot,
} from "@/lib/content/content-paths";
import { parseGraphRegistryRecords } from "@/lib/content/graph-registry-validation";

const projectRoot = getProjectRoot();
const graphRegistryRoot = getRegistryCollectionRoot("graphs");
const outputPath = join(
  getGeneratedContentRuntimeRoot(projectRoot),
  "graph-registry-runtime.generated.ts",
);

type GraphModuleDescriptor = {
  importName: string;
  importPath: string;
};

function toImportName(fileName: string): string {
  const baseName = fileName.replace(/\.json$/u, "");
  const camelCased = baseName.replace(/-([a-z0-9])/gu, (_, char: string) =>
    char.toUpperCase(),
  );
  return `${camelCased}GraphRecord`;
}

function readSortedGraphFiles(graphsRoot: string): string[] {
  return readdirSync(graphsRoot)
    .filter((entry) => entry.endsWith(".json"))
    .sort();
}

function buildGraphModuleDescriptors(
  graphFileNames: readonly string[],
): GraphModuleDescriptor[] {
  return graphFileNames.map((fileName) => ({
    importName: toImportName(fileName),
    importPath: `@/content/registry/graphs/${fileName}`,
  }));
}

function validateGraphRegistryFiles(
  graphsRoot: string,
  fileNames: readonly string[],
): void {
  parseGraphRegistryRecords(
    fileNames.map((fileName) => ({
      sourcePath: join(graphsRoot, fileName),
      value: JSON.parse(readFileSync(join(graphsRoot, fileName), "utf8")),
    })),
  );
}

export function generateGraphRegistryRuntimeSource(
  modules: readonly GraphModuleDescriptor[],
): string {
  const importLines = modules.map(
    ({ importName, importPath }) =>
      `import ${importName} from "${importPath}";`,
  );
  const recordNames = modules.map(({ importName }) => importName);

  return `${[
    "/**",
    " * Auto-generated from `src/content/registry/graphs`.",
    " * Do not edit this file by hand.",
    " */",
    ...importLines,
    'import { type GraphRecord, graphRecordSchema } from "@/lib/content/schemas";',
    "",
    "export const graphRecords: GraphRecord[] = [",
    ...recordNames.map(
      (recordName) => `  graphRecordSchema.parse(${recordName}),`,
    ),
    "];",
    "",
  ].join("\n")}`;
}

export type SyncGraphRegistryRuntimeModuleOptions = {
  graphsRoot?: string;
  outputPath?: string;
};

export function syncGraphRegistryRuntimeModule(
  options: SyncGraphRegistryRuntimeModuleOptions = {},
): {
  changed: boolean;
  graphCount: number;
  outputPath: string;
} {
  const resolvedGraphsRoot = options.graphsRoot ?? graphRegistryRoot;
  const resolvedOutputPath = options.outputPath ?? outputPath;
  const graphFileNames = readSortedGraphFiles(resolvedGraphsRoot);
  validateGraphRegistryFiles(resolvedGraphsRoot, graphFileNames);
  const source = generateGraphRegistryRuntimeSource(
    buildGraphModuleDescriptors(graphFileNames),
  );
  const existingSource = existsSync(resolvedOutputPath)
    ? readFileSync(resolvedOutputPath, "utf8")
    : undefined;

  if (existingSource === source) {
    return {
      changed: false,
      graphCount: graphFileNames.length,
      outputPath: resolvedOutputPath,
    };
  }

  mkdirSync(dirname(resolvedOutputPath), { recursive: true });
  writeFileSync(resolvedOutputPath, source, "utf8");
  return {
    changed: true,
    graphCount: graphFileNames.length,
    outputPath: resolvedOutputPath,
  };
}

if (import.meta.main) {
  const result = syncGraphRegistryRuntimeModule();
  const relativeOutputPath = relative(projectRoot, result.outputPath);
  const changeLabel = result.changed ? "updated" : "already current";
  console.log(
    `Graph registry runtime ${changeLabel}: ${relativeOutputPath} (${result.graphCount} graph records).`,
  );
}
