import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { getGeneratedContentRuntimeRoot } from "../src/lib/content/content-paths";
import { loadPublishedDocsRuntimeManifestSync } from "../src/lib/content/published-docs-registry-source";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..");
const outputPath = join(
  getGeneratedContentRuntimeRoot(repoRoot),
  "published-docs-registry.generated.ts",
);

const manifest = loadPublishedDocsRuntimeManifestSync("en");

function renderIdentifierKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/u.test(key) ? key : JSON.stringify(key);
}

function renderLiteral(value: unknown, indentLevel = 0): string {
  const indent = "  ".repeat(indentLevel);
  const nestedIndent = "  ".repeat(indentLevel + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }

    return [
      "[",
      ...value.map(
        (entry) => `${nestedIndent}${renderLiteral(entry, indentLevel + 1)},`,
      ),
      `${indent}]`,
    ].join("\n");
  }

  if (value && typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      return "{}";
    }

    return [
      "{",
      ...entries.map(
        ([key, entryValue]) =>
          `${nestedIndent}${renderIdentifierKey(key)}: ${renderLiteral(entryValue, indentLevel + 1)},`,
      ),
      `${indent}}`,
    ].join("\n");
  }

  return JSON.stringify(value);
}

const fileContents = `// Generated by scripts/generate-published-docs-registry.ts
// Do not edit by hand or commit regenerated output.

export const GENERATED_PUBLISHED_DOCS_ENTRIES = ${renderLiteral(
  manifest.entries,
)} as const;

export const GENERATED_PUBLISHED_DOCS_REGISTRY_IDS = ${renderLiteral(
  manifest.registryIds,
)} as const;

export const GENERATED_PUBLISHED_CONCEPT_SECTION_REGISTRY_IDS = ${renderLiteral(
  manifest.publishedConceptSectionRegistryIds,
)} as const;

export const GENERATED_MODULE_BACKED_CONCEPT_REGISTRY_IDS = ${renderLiteral(
  manifest.moduleBackedConceptRegistryIds,
)} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, fileContents);

const formatResult = spawnSync(
  "bunx",
  ["biome", "format", "--write", "--vcs-use-ignore-file=false", outputPath],
  {
    cwd: repoRoot,
    encoding: "utf8",
  },
);

if (formatResult.status !== 0) {
  throw new Error(
    `Failed to format ${relative(repoRoot, outputPath)}: ${
      formatResult.stderr || formatResult.stdout
    }`,
  );
}

console.log(`wrote ${relative(repoRoot, outputPath)}`);
