import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import {
  getGeneratedContentRuntimeRoot,
  getRegistryRoot,
} from "../src/lib/content/content-paths";
import { loadPublishedDocsRuntimeManifestSync } from "../src/lib/content/published-docs-registry-source";
import { renderTypescriptLiteral } from "../src/lib/content/render-typescript-literal";
import {
  deriveSidebarGrouping,
  readSidebarGroupingSourceRecords,
} from "../src/lib/content/sidebar-grouping-source";
import { writeFileIfChangedSync } from "../src/lib/content/write-file-if-changed";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..");
const outputPath = join(
  getGeneratedContentRuntimeRoot(repoRoot),
  "sidebar-grouping.generated.ts",
);

const records = readSidebarGroupingSourceRecords(getRegistryRoot());
const manifest = loadPublishedDocsRuntimeManifestSync("en");
const derived = deriveSidebarGrouping(records, manifest.entries);

const fileContents = `// Generated by scripts/generate-sidebar-grouping-runtime.ts
// Do not edit by hand or commit regenerated output.
//
// Source of truth is the \`sidebarGrouping\` field on each registry record under
// src/content/registry. Edit the record, not this file.

export const GENERATED_CONCEPTS_SIDEBAR_GROUP_BY_SLUG = ${renderTypescriptLiteral(
  derived.concepts,
)} as const;

export const GENERATED_DOCUMENTATION_SIDEBAR_MEMBERSHIP_BY_SLUG = ${renderTypescriptLiteral(
  derived.documentation,
)} as const;

export const GENERATED_REFERENCE_SIDEBAR_GROUP_BY_SLUG = ${renderTypescriptLiteral(
  derived.references,
)} as const;
`;

const result = writeFileIfChangedSync(outputPath, fileContents);
const relativeOutputPath = relative(repoRoot, outputPath);
console.log(`${result.changed ? "wrote" : "verified"} ${relativeOutputPath}`);
