import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { getGeneratedContentRuntimeRoot } from "../src/lib/content/content-paths";
import { loadPublishedDocsRuntimeManifestSync } from "../src/lib/content/published-docs-registry-source";
import { renderTypescriptLiteral } from "../src/lib/content/render-typescript-literal";
import { writeFileIfChangedSync } from "../src/lib/content/write-file-if-changed";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..");
const outputPath = join(
  getGeneratedContentRuntimeRoot(repoRoot),
  "published-docs-registry.generated.ts",
);

const manifest = loadPublishedDocsRuntimeManifestSync("en");

const fileContents = `// Generated by scripts/generate-published-docs-registry.ts
// Do not edit by hand or commit regenerated output.

export const GENERATED_PUBLISHED_DOCS_ENTRIES = ${renderTypescriptLiteral(
  manifest.entries,
)} as const;

export const GENERATED_PUBLISHED_DOCS_REGISTRY_IDS = ${renderTypescriptLiteral(
  manifest.registryIds,
)} as const;

export const GENERATED_PUBLISHED_CONCEPT_SECTION_REGISTRY_IDS = ${renderTypescriptLiteral(
  manifest.publishedConceptSectionRegistryIds,
)} as const;
`;

const result = writeFileIfChangedSync(outputPath, fileContents);
const relativeOutputPath = relative(repoRoot, outputPath);
console.log(`${result.changed ? "wrote" : "verified"} ${relativeOutputPath}`);
