import path from "node:path";
import { getGeneratedContentRuntimeRoot } from "@/lib/content/content-paths";
import { renderTypescriptLiteral } from "@/lib/content/render-typescript-literal";
import { deriveShippedLocalizedDocsManifest } from "@/lib/content/shipped-localized-docs.server";
import { writeFileIfChangedSync } from "@/lib/content/write-file-if-changed";

const outputPath = path.join(
  getGeneratedContentRuntimeRoot(process.cwd()),
  "shipped-localized-docs.generated.ts",
);
const manifest = deriveShippedLocalizedDocsManifest();

const fileContents = `// Generated by scripts/generate-shipped-localized-docs.ts
export const SHIPPED_LOCALIZED_DOCS = ${renderTypescriptLiteral(manifest)} as const;
`;

const result = writeFileIfChangedSync(outputPath, fileContents);
console.log(
  `${result.changed ? "Wrote" : "Verified"} shipped localized docs manifest at ${outputPath}`,
);
