import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { getGeneratedContentRuntimeRoot } from "@/lib/content/content-paths";
import { deriveShippedLocalizedDocsManifest } from "@/lib/content/shipped-localized-docs.server";
import { writeFileIfChangedSync } from "@/lib/content/write-file-if-changed";

const outputPath = path.join(
  getGeneratedContentRuntimeRoot(process.cwd()),
  "shipped-localized-docs.generated.ts",
);
const manifest = deriveShippedLocalizedDocsManifest();

const fileContents = `// Generated by scripts/generate-shipped-localized-docs.ts
export const SHIPPED_LOCALIZED_DOCS = ${JSON.stringify(manifest, null, 2)} as const;
`;

const tempDir = mkdtempSync(path.join(tmpdir(), "shipped-localized-docs-"));
const tempPath = path.join(tempDir, "shipped-localized-docs.generated.ts");

try {
  writeFileSync(tempPath, fileContents, "utf8");
  const formatResult = spawnSync(
    "bunx",
    ["biome", "format", "--write", tempPath],
    {
      cwd: process.cwd(),
      encoding: "utf8",
    },
  );

  if (formatResult.status !== 0) {
    throw new Error(
      `Failed to format ${outputPath}: ${formatResult.stderr || formatResult.stdout}`,
    );
  }

  const formatted = readFileSync(tempPath, "utf8");
  const result = writeFileIfChangedSync(outputPath, formatted);
  console.log(
    `${result.changed ? "Wrote" : "Verified"} shipped localized docs manifest at ${outputPath}`,
  );
} finally {
  rmSync(tempDir, { recursive: true, force: true });
}
